//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QLThietBi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMRootThietBiThuongHieu
    {
        public byte ID { get; set; }
        public string TenThuongHieu { get; set; }
    }
}
