//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QLThietBi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhiTangThietBiChiTiet
    {
        public int ID { get; set; }
        public int GhiTangThietBiID { get; set; }
        public int KhoPhongID { get; set; }
        public int ThietBiID { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> SoHieuTu { get; set; }
        public Nullable<int> SoHieuDen { get; set; }
        public decimal DonGia { get; set; }
        public decimal ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayHetBaoHanh { get; set; }
        public int NhaCungCapID { get; set; }
        public Nullable<int> ThuongHieuID { get; set; }
        public System.DateTime NgayMua { get; set; }
        public string GhiChu { get; set; }
        public long DonViID { get; set; }
        public Nullable<long> NguoiTaoID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<long> NguoiSuaID { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
