//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QLThietBi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public int ID { get; set; }
        public string TenNhaCungCap { get; set; }
        public string Diachi { get; set; }
        public string DienThoaiNguoiLienHe { get; set; }
        public string HoTenNguoiLienHe { get; set; }
        public bool isSuDung { get; set; }
        public Nullable<long> DonViID { get; set; }
        public Nullable<long> NguoiTaoID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<long> NguoiSuaID { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string GhiChu { get; set; }
    }
}
