//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QLThietBi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyThietBiEntities : DbContext
    {
        public QuanLyThietBiEntities()
            : base("name=QuanLyThietBiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMRootNHaCungCap> DMRootNHaCungCaps { get; set; }
        public virtual DbSet<DmRootThietBiDonViTinh> DmRootThietBiDonViTinhs { get; set; }
        public virtual DbSet<DMRootThietBiNhomThietBi> DMRootThietBiNhomThietBis { get; set; }
        public virtual DbSet<DMRootThietBiThuongHieu> DMRootThietBiThuongHieux { get; set; }
        public virtual DbSet<DMRootThietBiTrangThaiMuon> DMRootThietBiTrangThaiMuons { get; set; }
        public virtual DbSet<DMRootThietBiXepLoaiKhoPhong> DMRootThietBiXepLoaiKhoPhongs { get; set; }
        public virtual DbSet<GhiTangThietBi> GhiTangThietBis { get; set; }
        public virtual DbSet<GhiTangThietBiChiTiet> GhiTangThietBiChiTiets { get; set; }
        public virtual DbSet<KhoPhong> KhoPhongs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhomThietBi> NhomThietBis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
        public virtual DbSet<ThietBiChiTiet> ThietBiChiTiets { get; set; }
        public virtual DbSet<DangNhap> DangNhaps { get; set; }
    }
}
