//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QLThietBi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public int ID { get; set; }
        public string MaThietBi { get; set; }
        public string TenThietBi { get; set; }
        public int DonViTinhID { get; set; }
        public int NhomThietBiID { get; set; }
        public Nullable<int> DoiBaoTriID { get; set; }
        public Nullable<long> NhanSuBaoTri { get; set; }
        public Nullable<int> NhaCungCapID { get; set; }
        public Nullable<int> ThuongHieuID { get; set; }
        public bool isQuanLyTheoSoLuong { get; set; }
        public bool isQuanLyTheoSoHieu { get; set; }
        public bool isPhongBanSuDung { get; set; }
        public bool isThietBiTieuHao { get; set; }
        public bool isNhanVienSuDung { get; set; }
        public bool isSuDung { get; set; }
        public Nullable<int> ThuTu { get; set; }
        public string MucDichSuDung { get; set; }
        public string MoTa { get; set; }
        public Nullable<byte> TanSuatSoNgayBaoTri { get; set; }
        public Nullable<byte> ThoiLuongBaoTri { get; set; }
        public string AnhDaiDien { get; set; }
        public long DonViID { get; set; }
        public Nullable<long> NguoiTaoID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<long> NguoiSuaID { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
