//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.QLThietBi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBiChiTiet
    {
        public int ID { get; set; }
        public int GhiTangThietBiChiTietID { get; set; }
        public int ThietBiID { get; set; }
        public string TenKhac { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> SoHieu { get; set; }
        public bool isPhongBanSuDung { get; set; }
        public bool isNhanVienSuDung { get; set; }
        public bool isChuaSuDung { get; set; }
        public int PhongBanID { get; set; }
        public Nullable<long> NhanSuID { get; set; }
        public System.DateTime NgaySuDung { get; set; }
        public string SoSerial { get; set; }
        public Nullable<int> NamSanXuat { get; set; }
        public string CauHinh { get; set; }
        public string ViTriLapDat { get; set; }
        public string ViTri1 { get; set; }
        public string ViTri2 { get; set; }
        public string UrlRTSP1 { get; set; }
        public string UrlRTSP2 { get; set; }
        public Nullable<byte> ThietBiTrangThaiCAMID { get; set; }
        public string GhiChu { get; set; }
        public long DonViID { get; set; }
        public Nullable<long> NguoiTaoID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
